name: Events-API CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  deployment-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build docker image
        run: |
          docker build -t events-api:latest .

      - name: Run container
        run: |
          docker run -d -p 5000:5000 --name events-api-container events-api:latest
          
          echo "=== RUNNING CONTAINERS ==="
          docker ps -a
          
          echo "=== CONTAINER LOGS ==="
          docker logs events-api-container
          
          sleep 10
          curl -v http://127.0.0.1:5000/api/health || exit 1

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.13'

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Unit-Test
        run: |
          pytest -v

      - name: Cleanup
        if: always()
        run: |
            docker stop events-api-container
            docker rm events-api-container

  deploy:
    needs: deployment-test
    runs-on: ubuntu-latest
    environment: Prod

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Docker Login
        run: |
          echo "${{ secrets.DOCKER_ACCESS_TOKEN }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      
      - name: Build and Push Docker Image
        run: |
            docker buildx build --platform linux/amd64,linux/arm64 -t ${{ secrets.DOCKER_USERNAME }}/events-api:latest --push .

      - name: Deploy to Render
        run: |
          curl -X POST ${{secrets.RENDER_DEPLOY_HOOK}}

      - name: Wait for Deployment and Smoke Test
        run: |
          for i in {1..30}; do
            STATUS=$(curl -s -o /dev/null -w "%{http_code}" ${{secrets.RENDER_BASE_URL}}/api/health || echo "000")
            if [ "$STATUS" -eq 200 ]; then
              echo "Service is live!"
              exit 0
            fi
            echo "Service not ready yet, retrying in 10s..."
            sleep 10
          done
          echo "Service did not start successfully!"
          exit 1
      

